// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Components$ReVerv = require("./Components.bs.js");

var include = Components$ReVerv.BaseGameObject(/* module */[]);

var include$1 = Components$ReVerv.Origin(/* module */[]);

var include$2 = Components$ReVerv.Tint(/* module */[]);

var include$3 = Components$ReVerv.ScrollFactor(/* module */[]);

var include$4 = Components$ReVerv.Transform(/* module */[]);

var PBaseGO = include[0];

var makeBase = include[1];

var active = include[2];

var cameraFilter = include[3];

var type_ = include[4];

var tabIndex = include[5];

var state = include[6];

var stateInt = include[7];

var name = include[8];

var scene = include[9];

var data = include[10];

var arcadeBody = include[11];

var impactBody = include[12];

var matterBody = include[13];

var renderMask = include[14];

var renderFlags = include[15];

var parentContainer = include[16];

var ignoreDestroy = include[17];

var getIndexList = include[18];

var getData = include[19];

var removeInteractive = include[20];

var setName = include[21];

var setData = include[22];

var willRender = include[23];

var setState = include[24];

var setActive = include[25];

var setDataEnabled = include[26];

var O = include$1[0];

var displayOriginX = include$1[1];

var displayOriginY = include$1[2];

var originX = include$1[3];

var originY = include$1[4];

var setDisplayOrigin = include$1[5];

var setOrigin = include$1[6];

var setOriginFromFrame = include$1[7];

var updateDisplayOrigin = include$1[8];

var PTint = include$2[0];

var isTinted = include$2[1];

var tint = include$2[2];

var tintBottomLeft = include$2[3];

var tintBottomRight = include$2[4];

var tintFill = include$2[5];

var tintTopLeft = include$2[6];

var tintTopRight = include$2[7];

var clearTint = include$2[8];

var setTintFill = include$2[9];

var setTint = include$2[10];

var ScF = include$3[0];

var setScrollFactor = include$3[1];

var scrollFactorX = include$3[2];

var scrollFactorXF = include$3[3];

var scrollFactorY = include$3[4];

var scrollFactorYF = include$3[5];

var T = include$4[0];

var angle = include$4[1];

var angleF = include$4[2];

var rotation = include$4[3];

var rotationF = include$4[4];

var scale = include$4[5];

var scaleF = include$4[6];

var scaleX = include$4[7];

var scaleXF = include$4[8];

var scaleY = include$4[9];

var scaleYF = include$4[10];

var w = include$4[11];

var x = include$4[12];

var y = include$4[13];

var z = include$4[14];

var setX = include$4[15];

var setY = include$4[16];

var setW = include$4[17];

var setZ = include$4[18];

var setScale = include$4[19];

var setPosition = include$4[20];

var setRotation = include$4[21];

var setRotationF = include$4[22];

var getParentRotation = include$4[23];

var getParentRotationF = include$4[24];

exports.PBaseGO = PBaseGO;
exports.makeBase = makeBase;
exports.active = active;
exports.cameraFilter = cameraFilter;
exports.type_ = type_;
exports.tabIndex = tabIndex;
exports.state = state;
exports.stateInt = stateInt;
exports.name = name;
exports.scene = scene;
exports.data = data;
exports.arcadeBody = arcadeBody;
exports.impactBody = impactBody;
exports.matterBody = matterBody;
exports.renderMask = renderMask;
exports.renderFlags = renderFlags;
exports.parentContainer = parentContainer;
exports.ignoreDestroy = ignoreDestroy;
exports.getIndexList = getIndexList;
exports.getData = getData;
exports.removeInteractive = removeInteractive;
exports.setName = setName;
exports.setData = setData;
exports.willRender = willRender;
exports.setState = setState;
exports.setActive = setActive;
exports.setDataEnabled = setDataEnabled;
exports.O = O;
exports.displayOriginX = displayOriginX;
exports.displayOriginY = displayOriginY;
exports.originX = originX;
exports.originY = originY;
exports.setDisplayOrigin = setDisplayOrigin;
exports.setOrigin = setOrigin;
exports.setOriginFromFrame = setOriginFromFrame;
exports.updateDisplayOrigin = updateDisplayOrigin;
exports.PTint = PTint;
exports.isTinted = isTinted;
exports.tint = tint;
exports.tintBottomLeft = tintBottomLeft;
exports.tintBottomRight = tintBottomRight;
exports.tintFill = tintFill;
exports.tintTopLeft = tintTopLeft;
exports.tintTopRight = tintTopRight;
exports.clearTint = clearTint;
exports.setTintFill = setTintFill;
exports.setTint = setTint;
exports.ScF = ScF;
exports.setScrollFactor = setScrollFactor;
exports.scrollFactorX = scrollFactorX;
exports.scrollFactorXF = scrollFactorXF;
exports.scrollFactorY = scrollFactorY;
exports.scrollFactorYF = scrollFactorYF;
exports.T = T;
exports.angle = angle;
exports.angleF = angleF;
exports.rotation = rotation;
exports.rotationF = rotationF;
exports.scale = scale;
exports.scaleF = scaleF;
exports.scaleX = scaleX;
exports.scaleXF = scaleXF;
exports.scaleY = scaleY;
exports.scaleYF = scaleYF;
exports.w = w;
exports.x = x;
exports.y = y;
exports.z = z;
exports.setX = setX;
exports.setY = setY;
exports.setW = setW;
exports.setZ = setZ;
exports.setScale = setScale;
exports.setPosition = setPosition;
exports.setRotation = setRotation;
exports.setRotationF = setRotationF;
exports.getParentRotation = getParentRotation;
exports.getParentRotationF = getParentRotationF;
/* include Not a pure module */
