// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Components$ReVerv = require("./Components.bs.js");

var include = Components$ReVerv.Origin(/* module */[]);

var include$1 = Components$ReVerv.Tint(/* module */[]);

var include$2 = Components$ReVerv.ScrollFactor(/* module */[]);

var include$3 = Components$ReVerv.Transform(/* module */[]);

var O = include[0];

var displayOriginX = include[1];

var displayOriginY = include[2];

var originX = include[3];

var originY = include[4];

var setDisplayOrigin = include[5];

var setOrigin = include[6];

var setOriginFromFrame = include[7];

var updateDisplayOrigin = include[8];

var PTint = include$1[0];

var isTinted = include$1[1];

var tint = include$1[2];

var tintBottomLeft = include$1[3];

var tintBottomRight = include$1[4];

var tintFill = include$1[5];

var tintTopLeft = include$1[6];

var tintTopRight = include$1[7];

var clearTint = include$1[8];

var setTintFill = include$1[9];

var setTint = include$1[10];

var ScF = include$2[0];

var setScrollFactor = include$2[1];

var scrollFactorX = include$2[2];

var scrollFactorXF = include$2[3];

var scrollFactorY = include$2[4];

var scrollFactorYF = include$2[5];

var T = include$3[0];

var angle = include$3[1];

var angleF = include$3[2];

var rotation = include$3[3];

var rotationF = include$3[4];

var scale = include$3[5];

var scaleF = include$3[6];

var scaleX = include$3[7];

var scaleXF = include$3[8];

var scaleY = include$3[9];

var scaleYF = include$3[10];

var w = include$3[11];

var x = include$3[12];

var y = include$3[13];

var z = include$3[14];

var setX = include$3[15];

var setY = include$3[16];

var setW = include$3[17];

var setZ = include$3[18];

var setScale = include$3[19];

var setPosition = include$3[20];

var setRotation = include$3[21];

var setRotationF = include$3[22];

var getParentRotation = include$3[23];

var getParentRotationF = include$3[24];

exports.O = O;
exports.displayOriginX = displayOriginX;
exports.displayOriginY = displayOriginY;
exports.originX = originX;
exports.originY = originY;
exports.setDisplayOrigin = setDisplayOrigin;
exports.setOrigin = setOrigin;
exports.setOriginFromFrame = setOriginFromFrame;
exports.updateDisplayOrigin = updateDisplayOrigin;
exports.PTint = PTint;
exports.isTinted = isTinted;
exports.tint = tint;
exports.tintBottomLeft = tintBottomLeft;
exports.tintBottomRight = tintBottomRight;
exports.tintFill = tintFill;
exports.tintTopLeft = tintTopLeft;
exports.tintTopRight = tintTopRight;
exports.clearTint = clearTint;
exports.setTintFill = setTintFill;
exports.setTint = setTint;
exports.ScF = ScF;
exports.setScrollFactor = setScrollFactor;
exports.scrollFactorX = scrollFactorX;
exports.scrollFactorXF = scrollFactorXF;
exports.scrollFactorY = scrollFactorY;
exports.scrollFactorYF = scrollFactorYF;
exports.T = T;
exports.angle = angle;
exports.angleF = angleF;
exports.rotation = rotation;
exports.rotationF = rotationF;
exports.scale = scale;
exports.scaleF = scaleF;
exports.scaleX = scaleX;
exports.scaleXF = scaleXF;
exports.scaleY = scaleY;
exports.scaleYF = scaleYF;
exports.w = w;
exports.x = x;
exports.y = y;
exports.z = z;
exports.setX = setX;
exports.setY = setY;
exports.setW = setW;
exports.setZ = setZ;
exports.setScale = setScale;
exports.setPosition = setPosition;
exports.setRotation = setRotation;
exports.setRotationF = setRotationF;
exports.getParentRotation = getParentRotation;
exports.getParentRotationF = getParentRotationF;
/* include Not a pure module */
