// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var VBase$ReVerv = require("./VBase.bs.js");
var Components$ReVerv = require("./Components.bs.js");

var include = Components$ReVerv.Flip(/* module */[]);

var include$1 = Components$ReVerv.Tint(/* module */[]);

function backgroundColor(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.backgroundColor;
              }), param);
}

function cameraManager(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.cameraManager;
              }), param);
}

function id(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.id;
              }), param);
}

function originX(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.originX;
              }), param);
}

function originY(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.originY;
              }), param);
}

var Camera2D_001 = /* F */include[0];

var Camera2D_002 = /* flipX */include[1];

var Camera2D_003 = /* flipY */include[2];

var Camera2D_004 = /* resetFlip */include[3];

var Camera2D_005 = /* setFlip */include[4];

var Camera2D_006 = /* setFlipX */include[5];

var Camera2D_007 = /* setFlipY */include[6];

var Camera2D_008 = /* toggleFlipX */include[7];

var Camera2D_009 = /* toggleFlipY */include[8];

var Camera2D_010 = /* PTint */include$1[0];

var Camera2D_011 = /* isTinted */include$1[1];

var Camera2D_012 = /* tint */include$1[2];

var Camera2D_013 = /* tintBottomLeft */include$1[3];

var Camera2D_014 = /* tintBottomRight */include$1[4];

var Camera2D_015 = /* tintFill */include$1[5];

var Camera2D_016 = /* tintTopLeft */include$1[6];

var Camera2D_017 = /* tintTopRight */include$1[7];

var Camera2D_018 = /* clearTint */include$1[8];

var Camera2D_019 = /* setTintFill */include$1[9];

var Camera2D_020 = /* setTint */include$1[10];

var Camera2D = /* module */[
  /* PCamera2D */0,
  Camera2D_001,
  Camera2D_002,
  Camera2D_003,
  Camera2D_004,
  Camera2D_005,
  Camera2D_006,
  Camera2D_007,
  Camera2D_008,
  Camera2D_009,
  Camera2D_010,
  Camera2D_011,
  Camera2D_012,
  Camera2D_013,
  Camera2D_014,
  Camera2D_015,
  Camera2D_016,
  Camera2D_017,
  Camera2D_018,
  Camera2D_019,
  Camera2D_020,
  /* backgroundColor */backgroundColor,
  /* cameraManager */cameraManager,
  /* id */id,
  /* originX */originX,
  /* originY */originY
];

exports.Camera2D = Camera2D;
/* include Not a pure module */
