// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Tablecloth = require("tablecloth-bucklescript/src/tablecloth.bs.js");
var VBase$ReVerv = require("./VBase.bs.js");
var PhaserAPI$ReVerv = require("./PhaserAPI.bs.js");
var Components$ReVerv = require("./Components.bs.js");

PhaserAPI$ReVerv.GameObjects[/* BaseGameObject */0](/* module */[]);

var include = Components$ReVerv.Alpha(/* module */[]);

var include$1 = Components$ReVerv.Depth(/* module */[]);

function $bang$great(image) {
  return /* Container */[image];
}

function lift(image) {
  return /* Container */[image];
}

function $less$less$eq(vervContainer, f) {
  return /* Container */[Curry._1(f, vervContainer[0])];
}

function setPipeline(pipeline, vervImage) {
  return VBase$ReVerv.map((function (__x) {
                return __x.setPipeline(undefined);
              }), vervImage);
}

function phaserImage(vervImage) {
  return VBase$ReVerv.flatMap(Tablecloth.identity, vervImage);
}

var include$2 = Components$ReVerv.Origin(/* module */[]);

var include$3 = Components$ReVerv.Flip(/* module */[]);

var include$4 = Components$ReVerv.ScrollFactor(/* module */[]);

var include$5 = Components$ReVerv.Transform(/* module */[]);

var PImg = 0;

var PAlpha = include[0];

var alpha = include[1];

var alphaF = include[2];

var alphaTopLeft = include[3];

var alphaTopLeftF = include[4];

var alphaTopRight = include[5];

var alphaTopRightF = include[6];

var alphaBottomLeft = include[7];

var alphaBottomLeftF = include[8];

var alphaBottomRight = include[9];

var alphaBottomRightF = include[10];

var clearAlpha = include[11];

var setAlpha = include[12];

var PDepth = include$1[0];

var depth = include$1[1];

var depthF = include$1[2];

var setDepth = include$1[3];

var O = include$2[0];

var displayOriginX = include$2[1];

var displayOriginY = include$2[2];

var originX = include$2[3];

var originY = include$2[4];

var setDisplayOrigin = include$2[5];

var setOrigin = include$2[6];

var setOriginFromFrame = include$2[7];

var updateDisplayOrigin = include$2[8];

var F = include$3[0];

var flipX = include$3[1];

var flipY = include$3[2];

var resetFlip = include$3[3];

var setFlip = include$3[4];

var setFlipX = include$3[5];

var setFlipY = include$3[6];

var toggleFlipX = include$3[7];

var toggleFlipY = include$3[8];

var ScF = include$4[0];

var setScrollFactor = include$4[1];

var scrollFactorX = include$4[2];

var scrollFactorXF = include$4[3];

var scrollFactorY = include$4[4];

var scrollFactorYF = include$4[5];

var T = include$5[0];

var angle = include$5[1];

var angleF = include$5[2];

var rotation = include$5[3];

var rotationF = include$5[4];

var scale = include$5[5];

var scaleF = include$5[6];

var scaleX = include$5[7];

var scaleXF = include$5[8];

var scaleY = include$5[9];

var scaleYF = include$5[10];

var w = include$5[11];

var x = include$5[12];

var y = include$5[13];

var z = include$5[14];

var setX = include$5[15];

var setY = include$5[16];

var setW = include$5[17];

var setZ = include$5[18];

var setScale = include$5[19];

var setPosition = include$5[20];

var setRotation = include$5[21];

var setRotationF = include$5[22];

var getParentRotation = include$5[23];

var getParentRotationF = include$5[24];

exports.PImg = PImg;
exports.PAlpha = PAlpha;
exports.alpha = alpha;
exports.alphaF = alphaF;
exports.alphaTopLeft = alphaTopLeft;
exports.alphaTopLeftF = alphaTopLeftF;
exports.alphaTopRight = alphaTopRight;
exports.alphaTopRightF = alphaTopRightF;
exports.alphaBottomLeft = alphaBottomLeft;
exports.alphaBottomLeftF = alphaBottomLeftF;
exports.alphaBottomRight = alphaBottomRight;
exports.alphaBottomRightF = alphaBottomRightF;
exports.clearAlpha = clearAlpha;
exports.setAlpha = setAlpha;
exports.PDepth = PDepth;
exports.depth = depth;
exports.depthF = depthF;
exports.setDepth = setDepth;
exports.$bang$great = $bang$great;
exports.lift = lift;
exports.$less$less$eq = $less$less$eq;
exports.setPipeline = setPipeline;
exports.phaserImage = phaserImage;
exports.O = O;
exports.displayOriginX = displayOriginX;
exports.displayOriginY = displayOriginY;
exports.originX = originX;
exports.originY = originY;
exports.setDisplayOrigin = setDisplayOrigin;
exports.setOrigin = setOrigin;
exports.setOriginFromFrame = setOriginFromFrame;
exports.updateDisplayOrigin = updateDisplayOrigin;
exports.F = F;
exports.flipX = flipX;
exports.flipY = flipY;
exports.resetFlip = resetFlip;
exports.setFlip = setFlip;
exports.setFlipX = setFlipX;
exports.setFlipY = setFlipY;
exports.toggleFlipX = toggleFlipX;
exports.toggleFlipY = toggleFlipY;
exports.ScF = ScF;
exports.setScrollFactor = setScrollFactor;
exports.scrollFactorX = scrollFactorX;
exports.scrollFactorXF = scrollFactorXF;
exports.scrollFactorY = scrollFactorY;
exports.scrollFactorYF = scrollFactorYF;
exports.T = T;
exports.angle = angle;
exports.angleF = angleF;
exports.rotation = rotation;
exports.rotationF = rotationF;
exports.scale = scale;
exports.scaleF = scaleF;
exports.scaleX = scaleX;
exports.scaleXF = scaleXF;
exports.scaleY = scaleY;
exports.scaleYF = scaleYF;
exports.w = w;
exports.x = x;
exports.y = y;
exports.z = z;
exports.setX = setX;
exports.setY = setY;
exports.setW = setW;
exports.setZ = setZ;
exports.setScale = setScale;
exports.setPosition = setPosition;
exports.setRotation = setRotation;
exports.setRotationF = setRotationF;
exports.getParentRotation = getParentRotation;
exports.getParentRotationF = getParentRotationF;
/*  Not a pure module */
