// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Verv$ReVerv = require("./Verv.bs.js");

var sceneCreate = Verv$ReVerv.dataCallback((function (scene, param) {
        var SceneLoader = Verv$ReVerv.MakeLoader(/* module */[/* scene */scene]);
        var SceneFactory = Verv$ReVerv.MakeGameObjFactory(/* module */[/* scene */scene]);
        var loader = Curry._2(SceneLoader[/* loadImage */3], "abc", /* array */["./abcFile"]);
        var image = Curry._5(SceneFactory[/* addImage */1], 0, 0, "abc", "abc", /* () */0);
        var test = Verv$ReVerv.$$Image[/* setX */4](30, Verv$ReVerv.$$Image[/* !> */1](image));
        console.log(test);
        console.log(loader);
        var text = scene.add.text(64, 200, "Hello World");
        return text.setColor("white");
      }));

var titleScene = Verv$ReVerv.createScene("title", undefined, undefined, Caml_option.some(sceneCreate), undefined, /* () */0);

var game = Verv$ReVerv.createGame(Verv$ReVerv.auto, "phaser-example", 800, 600, titleScene);

exports.sceneCreate = sceneCreate;
exports.titleScene = titleScene;
exports.game = game;
/* sceneCreate Not a pure module */
