// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Verv$ReVerv = require("./Verv.bs.js");
var Image$ReVerv = require("./Image.bs.js");
var Scene$ReVerv = require("./Scene.bs.js");
var VBase$ReVerv = require("./VBase.bs.js");

function sceneCreate(scene, param) {
  var SceneLoader = Verv$ReVerv.MakeLoader(/* module */[/* scene */scene]);
  var SceneFactory = Verv$ReVerv.MakeGameObjFactory(/* module */[/* scene */scene]);
  Curry._2(SceneLoader[/* loadImage */3], "abc", /* array */["./abcFile"]);
  var image = Curry._5(SceneFactory[/* addImage */2], 0, 0, "abc", "abc", /* () */0);
  var sprite = Curry._5(SceneFactory[/* addSprite */3], 30, 30, "abc", "abc", /* () */0);
  var test = Curry._2(Image$ReVerv.setY, 30, Curry._2(Image$ReVerv.setX, 30, image));
  console.log(Curry._1(Image$ReVerv.name, test));
  console.log(Curry._1(Image$ReVerv.state, test));
  console.log(sprite);
  Curry._4(SceneFactory[/* addText */7], 64, 64, "Hello from ReasonML", "white");
  return /* () */0;
}

var titleScene = Scene$ReVerv.createScene("title", undefined, undefined, sceneCreate, undefined, /* () */0);

var game = Verv$ReVerv.createGame(Verv$ReVerv.auto, "phaser-example", 800, 600, titleScene);

var match = VBase$ReVerv.useReducer((function (state, action) {
        switch (action.tag | 0) {
          case 0 : 
              return /* record */[
                      /* title */action[0],
                      /* currentScene */state[/* currentScene */1],
                      /* game */state[/* game */2]
                    ];
          case 1 : 
              if (action[0] === "Title") {
                return /* record */[
                        /* title */state[/* title */0],
                        /* currentScene */titleScene,
                        /* game */state[/* game */2]
                      ];
              } else {
                return state;
              }
          case 2 : 
              return state;
          
        }
      }), /* record */[
      /* title */"ReasonML Game",
      /* currentScene */titleScene,
      /* game */game
    ]);

var gameDispatcher = match[1];

var game$1 = match[0];

console.log(game$1);

console.log(Curry._1(gameDispatcher, /* ChangeTitle */Block.__(0, ["Freljord"])));

exports.sceneCreate = sceneCreate;
exports.titleScene = titleScene;
exports.game = game$1;
exports.gameDispatcher = gameDispatcher;
/* titleScene Not a pure module */
