// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Keys = /* module */[];

var Mouse = /* module */[];

exports.Keys = Keys;
exports.Mouse = Mouse;
/* No side effect */
