// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var VBase$ReVerv = require("./VBase.bs.js");
var PhaserAPI$ReVerv = require("./PhaserAPI.bs.js");

function isUp(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.isUp;
              }), param);
}

function isDown(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.isDown;
              }), param);
}

function keyCode(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.keyCode;
              }), param);
}

function $$location(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.location;
              }), param);
}

function shiftKey(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.shiftKey;
              }), param);
}

function timeUp(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.timeUp;
              }), param);
}

function timeDown(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.timeDown;
              }), param);
}

function metaKey(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.metaKey;
              }), param);
}

function altKey(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.altKey;
              }), param);
}

function ctrlKey(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.ctrlKey;
              }), param);
}

function enabled(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.enabled;
              }), param);
}

function repeats(param) {
  return VBase$ReVerv.flatMap((function (prim) {
                return prim.repeats;
              }), param);
}

PhaserAPI$ReVerv.Events[/* EventEmitter */0](/* module */[]);

var Keys = /* module */[
  /* PKey */0,
  /* isUp */isUp,
  /* isDown */isDown,
  /* keyCode */keyCode,
  /* location */$$location,
  /* shiftKey */shiftKey,
  /* timeUp */timeUp,
  /* timeDown */timeDown,
  /* metaKey */metaKey,
  /* altKey */altKey,
  /* ctrlKey */ctrlKey,
  /* enabled */enabled,
  /* repeats */repeats
];

var Mouse = /* module */[];

exports.Keys = Keys;
exports.Mouse = Mouse;
/*  Not a pure module */
