// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function EventEmitter(E) {
  return /* module */[];
}

var Events = /* module */[/* EventEmitter */EventEmitter];

var Vector2 = /* module */[];

var $$Math = /* module */[/* Vector2 */Vector2];

var $$Gamepad = /* module */[];

var Key = /* module */[];

var Keyboard = /* module */[/* Key */Key];

var Mouse = /* module */[];

var $$Touch = /* module */[];

var Input = /* module */[
  /* Gamepad */$$Gamepad,
  /* Keyboard */Keyboard,
  /* Mouse */Mouse,
  /* Touch */$$Touch
];

var Game = /* module */[];

var Tilemaps = /* module */[];

var $$Text = /* module */[];

var Polygon = /* module */[];

var $$Image = /* module */[];

var Zone = /* module */[];

var Graphics = /* module */[];

var GameObjects = /* module */[
  /* Text */$$Text,
  /* Polygon */Polygon,
  /* Image */$$Image,
  /* Zone */Zone,
  /* Graphics */Graphics
];

var Body = /* module */[];

var Arcade = /* module */[/* Body */Body];

var Body$1 = /* module */[];

var Impact = /* module */[/* Body */Body$1];

var Body$2 = /* module */[];

var Matter = /* module */[/* Body */Body$2];

var Physics = /* module */[
  /* Arcade */Arcade,
  /* Impact */Impact,
  /* Matter */Matter
];

var Scene = /* module */[];

var BlendModes = /* module */[];

function tweenEquationStr(tweenEquation) {
  switch (tweenEquation) {
    case 0 : 
        return "Power0";
    case 1 : 
        return "Power1";
    case 2 : 
        return "Power2";
    case 3 : 
        return "Power3";
    case 4 : 
        return "Power4";
    case 5 : 
        return "Linear";
    case 6 : 
        return "Quad";
    case 7 : 
        return "Cubic";
    case 8 : 
        return "Quart";
    case 9 : 
        return "Quint";
    case 10 : 
        return "Sine";
    case 11 : 
        return "Expo";
    case 12 : 
        return "Circ";
    case 13 : 
        return "Elastic";
    case 14 : 
        return "Back";
    case 15 : 
        return "Bounce";
    case 16 : 
        return "Stepped";
    case 17 : 
        return "Quad.easeIn";
    case 18 : 
        return "Cubic.easeIn";
    case 19 : 
        return "Quint.easeIn";
    case 20 : 
        return "Quart.easeIn";
    case 21 : 
        return "Sine.easeIn";
    case 22 : 
        return "Expo.easeIn";
    case 23 : 
        return "Circ.easeIn";
    case 24 : 
        return "Back.easeIn";
    case 25 : 
        return "Bounce.easeIn";
    case 26 : 
        return "Quad.easeOut";
    case 27 : 
        return "Cubic.easeOut";
    case 28 : 
        return "Quart.easeOut";
    case 29 : 
        return "Quint.easeOut";
    case 30 : 
        return "Sine.easeOut";
    case 31 : 
        return "Expo.easeOut";
    case 32 : 
        return "Circ.easeOut";
    case 33 : 
        return "Back.easeOut";
    case 34 : 
        return "Bounce.easeOut";
    case 35 : 
        return "Quad.easeInOut";
    case 36 : 
        return "Cubic.easeInOut";
    case 37 : 
        return "Quart.easeInOut";
    case 38 : 
        return "Quint.easeInOut";
    case 39 : 
        return "Sine.easeInOut";
    case 40 : 
        return "Expo.easeInOut";
    case 41 : 
        return "Circ.easeInOut";
    case 42 : 
        return "Back.easeInOut";
    case 43 : 
        return "Bounce.easeInOut";
    
  }
}

var TweenManager = /* module */[/* tweenEquationStr */tweenEquationStr];

var DOM = /* module */[];

var GameObjectFactory = /* module */[];

var LoaderPlugin = /* module */[];

exports.Events = Events;
exports.$$Math = $$Math;
exports.Input = Input;
exports.Game = Game;
exports.Tilemaps = Tilemaps;
exports.GameObjects = GameObjects;
exports.Physics = Physics;
exports.Scene = Scene;
exports.BlendModes = BlendModes;
exports.TweenManager = TweenManager;
exports.DOM = DOM;
exports.GameObjectFactory = GameObjectFactory;
exports.LoaderPlugin = LoaderPlugin;
/* No side effect */
