// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Phaser = require("phaser");
var VBase$ReVerv = require("./VBase.bs.js");

function createScene(key, init, preload, create, update, param) {
  var vervScene = new Phaser.Scene({
        key: key
      });
  var sceneUpdateCallback = function (fn) {
    return (function (time, delta) {
        var scene = this ;
        return Curry._3(fn, scene, time, delta);
      });
  };
  if (init !== undefined) {
    vervScene.init = VBase$ReVerv.dataCallback(init);
  }
  if (create !== undefined) {
    vervScene.create = VBase$ReVerv.dataCallback(create);
  }
  if (preload !== undefined) {
    vervScene.preload = VBase$ReVerv.zeroCallback(preload);
  }
  if (update !== undefined) {
    vervScene.update = sceneUpdateCallback(update);
  }
  return vervScene;
}

exports.createScene = createScene;
/* phaser Not a pure module */
