// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var PhaserAPI$ReVerv = require("./PhaserAPI.bs.js");
var Components$ReVerv = require("./Components.bs.js");

function addText(scene, x, y, text, color) {
  var text$1 = scene.add.text(x, y, text);
  return text$1.setColor(color);
}

PhaserAPI$ReVerv.GameObjects[/* BaseGameObject */0](/* module */[]);

var include = Components$ReVerv.BlendMode(/* module */[]);

var include$1 = Components$ReVerv.Origin(/* module */[]);

var include$2 = Components$ReVerv.Tint(/* module */[]);

var include$3 = Components$ReVerv.Flip(/* module */[]);

var include$4 = Components$ReVerv.ScrollFactor(/* module */[]);

var include$5 = Components$ReVerv.Transform(/* module */[]);

var include$6 = Components$ReVerv.Visible(/* module */[]);

var B = include[0];

var blendMode = include[1];

var blendModeStr = include[2];

var setBlendModeStr = include[3];

var setBlendMode = include[4];

var O = include$1[0];

var displayOriginX = include$1[1];

var displayOriginY = include$1[2];

var originX = include$1[3];

var originY = include$1[4];

var setDisplayOrigin = include$1[5];

var setOrigin = include$1[6];

var setOriginFromFrame = include$1[7];

var updateDisplayOrigin = include$1[8];

var PTint = include$2[0];

var isTinted = include$2[1];

var tint = include$2[2];

var tintBottomLeft = include$2[3];

var tintBottomRight = include$2[4];

var tintFill = include$2[5];

var tintTopLeft = include$2[6];

var tintTopRight = include$2[7];

var clearTint = include$2[8];

var setTintFill = include$2[9];

var setTint = include$2[10];

var F = include$3[0];

var flipX = include$3[1];

var flipY = include$3[2];

var resetFlip = include$3[3];

var setFlip = include$3[4];

var setFlipX = include$3[5];

var setFlipY = include$3[6];

var toggleFlipX = include$3[7];

var toggleFlipY = include$3[8];

var ScF = include$4[0];

var setScrollFactor = include$4[1];

var scrollFactorX = include$4[2];

var scrollFactorXF = include$4[3];

var scrollFactorY = include$4[4];

var scrollFactorYF = include$4[5];

var T = include$5[0];

var angle = include$5[1];

var angleF = include$5[2];

var rotation = include$5[3];

var rotationF = include$5[4];

var scale = include$5[5];

var scaleF = include$5[6];

var scaleX = include$5[7];

var scaleXF = include$5[8];

var scaleY = include$5[9];

var scaleYF = include$5[10];

var w = include$5[11];

var x = include$5[12];

var y = include$5[13];

var z = include$5[14];

var setX = include$5[15];

var setY = include$5[16];

var setW = include$5[17];

var setZ = include$5[18];

var setScale = include$5[19];

var setPosition = include$5[20];

var setRotation = include$5[21];

var setRotationF = include$5[22];

var getParentRotation = include$5[23];

var getParentRotationF = include$5[24];

var V = include$6[0];

var visible = include$6[1];

var setVisible = include$6[2];

exports.addText = addText;
exports.B = B;
exports.blendMode = blendMode;
exports.blendModeStr = blendModeStr;
exports.setBlendModeStr = setBlendModeStr;
exports.setBlendMode = setBlendMode;
exports.O = O;
exports.displayOriginX = displayOriginX;
exports.displayOriginY = displayOriginY;
exports.originX = originX;
exports.originY = originY;
exports.setDisplayOrigin = setDisplayOrigin;
exports.setOrigin = setOrigin;
exports.setOriginFromFrame = setOriginFromFrame;
exports.updateDisplayOrigin = updateDisplayOrigin;
exports.PTint = PTint;
exports.isTinted = isTinted;
exports.tint = tint;
exports.tintBottomLeft = tintBottomLeft;
exports.tintBottomRight = tintBottomRight;
exports.tintFill = tintFill;
exports.tintTopLeft = tintTopLeft;
exports.tintTopRight = tintTopRight;
exports.clearTint = clearTint;
exports.setTintFill = setTintFill;
exports.setTint = setTint;
exports.F = F;
exports.flipX = flipX;
exports.flipY = flipY;
exports.resetFlip = resetFlip;
exports.setFlip = setFlip;
exports.setFlipX = setFlipX;
exports.setFlipY = setFlipY;
exports.toggleFlipX = toggleFlipX;
exports.toggleFlipY = toggleFlipY;
exports.ScF = ScF;
exports.setScrollFactor = setScrollFactor;
exports.scrollFactorX = scrollFactorX;
exports.scrollFactorXF = scrollFactorXF;
exports.scrollFactorY = scrollFactorY;
exports.scrollFactorYF = scrollFactorYF;
exports.T = T;
exports.angle = angle;
exports.angleF = angleF;
exports.rotation = rotation;
exports.rotationF = rotationF;
exports.scale = scale;
exports.scaleF = scaleF;
exports.scaleX = scaleX;
exports.scaleXF = scaleXF;
exports.scaleY = scaleY;
exports.scaleYF = scaleYF;
exports.w = w;
exports.x = x;
exports.y = y;
exports.z = z;
exports.setX = setX;
exports.setY = setY;
exports.setW = setW;
exports.setZ = setZ;
exports.setScale = setScale;
exports.setPosition = setPosition;
exports.setRotation = setRotation;
exports.setRotationF = setRotationF;
exports.getParentRotation = getParentRotation;
exports.getParentRotationF = getParentRotationF;
exports.V = V;
exports.visible = visible;
exports.setVisible = setVisible;
/*  Not a pure module */
