// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var VBase$ReVerv = require("./VBase.bs.js");
var Components$ReVerv = require("./Components.bs.js");

function setColor(color, container) {
  return VBase$ReVerv.map((function (__x) {
                return __x.setColor(color);
              }), container);
}

var include = Components$ReVerv.BaseGameObject(/* module */[]);

var include$1 = Components$ReVerv.BlendMode(/* module */[]);

var include$2 = Components$ReVerv.Origin(/* module */[]);

var include$3 = Components$ReVerv.Tint(/* module */[]);

var include$4 = Components$ReVerv.Flip(/* module */[]);

var include$5 = Components$ReVerv.ScrollFactor(/* module */[]);

var include$6 = Components$ReVerv.Transform(/* module */[]);

var include$7 = Components$ReVerv.Visible(/* module */[]);

var PText = 0;

var PBaseGO = include[0];

var makeBase = include[1];

var active = include[2];

var cameraFilter = include[3];

var type_ = include[4];

var tabIndex = include[5];

var state = include[6];

var stateInt = include[7];

var name = include[8];

var scene = include[9];

var data = include[10];

var arcadeBody = include[11];

var impactBody = include[12];

var matterBody = include[13];

var renderMask = include[14];

var renderFlags = include[15];

var parentContainer = include[16];

var ignoreDestroy = include[17];

var getIndexList = include[18];

var getData = include[19];

var removeInteractive = include[20];

var setName = include[21];

var setData = include[22];

var willRender = include[23];

var setState = include[24];

var setActive = include[25];

var setDataEnabled = include[26];

var B = include$1[0];

var blendMode = include$1[1];

var blendModeStr = include$1[2];

var setBlendModeStr = include$1[3];

var setBlendMode = include$1[4];

var O = include$2[0];

var displayOriginX = include$2[1];

var displayOriginY = include$2[2];

var originX = include$2[3];

var originY = include$2[4];

var setDisplayOrigin = include$2[5];

var setOrigin = include$2[6];

var setOriginFromFrame = include$2[7];

var updateDisplayOrigin = include$2[8];

var PTint = include$3[0];

var isTinted = include$3[1];

var tint = include$3[2];

var tintBottomLeft = include$3[3];

var tintBottomRight = include$3[4];

var tintFill = include$3[5];

var tintTopLeft = include$3[6];

var tintTopRight = include$3[7];

var clearTint = include$3[8];

var setTintFill = include$3[9];

var setTint = include$3[10];

var F = include$4[0];

var flipX = include$4[1];

var flipY = include$4[2];

var resetFlip = include$4[3];

var setFlip = include$4[4];

var setFlipX = include$4[5];

var setFlipY = include$4[6];

var toggleFlipX = include$4[7];

var toggleFlipY = include$4[8];

var ScF = include$5[0];

var setScrollFactor = include$5[1];

var scrollFactorX = include$5[2];

var scrollFactorXF = include$5[3];

var scrollFactorY = include$5[4];

var scrollFactorYF = include$5[5];

var T = include$6[0];

var angle = include$6[1];

var angleF = include$6[2];

var rotation = include$6[3];

var rotationF = include$6[4];

var scale = include$6[5];

var scaleF = include$6[6];

var scaleX = include$6[7];

var scaleXF = include$6[8];

var scaleY = include$6[9];

var scaleYF = include$6[10];

var w = include$6[11];

var x = include$6[12];

var y = include$6[13];

var z = include$6[14];

var setX = include$6[15];

var setY = include$6[16];

var setW = include$6[17];

var setZ = include$6[18];

var setScale = include$6[19];

var setPosition = include$6[20];

var setRotation = include$6[21];

var setRotationF = include$6[22];

var getParentRotation = include$6[23];

var getParentRotationF = include$6[24];

var V = include$7[0];

var visible = include$7[1];

var setVisible = include$7[2];

exports.PText = PText;
exports.setColor = setColor;
exports.PBaseGO = PBaseGO;
exports.makeBase = makeBase;
exports.active = active;
exports.cameraFilter = cameraFilter;
exports.type_ = type_;
exports.tabIndex = tabIndex;
exports.state = state;
exports.stateInt = stateInt;
exports.name = name;
exports.scene = scene;
exports.data = data;
exports.arcadeBody = arcadeBody;
exports.impactBody = impactBody;
exports.matterBody = matterBody;
exports.renderMask = renderMask;
exports.renderFlags = renderFlags;
exports.parentContainer = parentContainer;
exports.ignoreDestroy = ignoreDestroy;
exports.getIndexList = getIndexList;
exports.getData = getData;
exports.removeInteractive = removeInteractive;
exports.setName = setName;
exports.setData = setData;
exports.willRender = willRender;
exports.setState = setState;
exports.setActive = setActive;
exports.setDataEnabled = setDataEnabled;
exports.B = B;
exports.blendMode = blendMode;
exports.blendModeStr = blendModeStr;
exports.setBlendModeStr = setBlendModeStr;
exports.setBlendMode = setBlendMode;
exports.O = O;
exports.displayOriginX = displayOriginX;
exports.displayOriginY = displayOriginY;
exports.originX = originX;
exports.originY = originY;
exports.setDisplayOrigin = setDisplayOrigin;
exports.setOrigin = setOrigin;
exports.setOriginFromFrame = setOriginFromFrame;
exports.updateDisplayOrigin = updateDisplayOrigin;
exports.PTint = PTint;
exports.isTinted = isTinted;
exports.tint = tint;
exports.tintBottomLeft = tintBottomLeft;
exports.tintBottomRight = tintBottomRight;
exports.tintFill = tintFill;
exports.tintTopLeft = tintTopLeft;
exports.tintTopRight = tintTopRight;
exports.clearTint = clearTint;
exports.setTintFill = setTintFill;
exports.setTint = setTint;
exports.F = F;
exports.flipX = flipX;
exports.flipY = flipY;
exports.resetFlip = resetFlip;
exports.setFlip = setFlip;
exports.setFlipX = setFlipX;
exports.setFlipY = setFlipY;
exports.toggleFlipX = toggleFlipX;
exports.toggleFlipY = toggleFlipY;
exports.ScF = ScF;
exports.setScrollFactor = setScrollFactor;
exports.scrollFactorX = scrollFactorX;
exports.scrollFactorXF = scrollFactorXF;
exports.scrollFactorY = scrollFactorY;
exports.scrollFactorYF = scrollFactorYF;
exports.T = T;
exports.angle = angle;
exports.angleF = angleF;
exports.rotation = rotation;
exports.rotationF = rotationF;
exports.scale = scale;
exports.scaleF = scaleF;
exports.scaleX = scaleX;
exports.scaleXF = scaleXF;
exports.scaleY = scaleY;
exports.scaleYF = scaleYF;
exports.w = w;
exports.x = x;
exports.y = y;
exports.z = z;
exports.setX = setX;
exports.setY = setY;
exports.setW = setW;
exports.setZ = setZ;
exports.setScale = setScale;
exports.setPosition = setPosition;
exports.setRotation = setRotation;
exports.setRotationF = setRotationF;
exports.getParentRotation = getParentRotation;
exports.getParentRotationF = getParentRotationF;
exports.V = V;
exports.visible = visible;
exports.setVisible = setVisible;
/* include Not a pure module */
