// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function map(f, vervComponent) {
  return /* Container */[Curry._1(f, vervComponent[0])];
}

function flatMap(f, vervComponent) {
  return Curry._1(f, vervComponent[0]);
}

exports.map = map;
exports.flatMap = flatMap;
/* No side effect */
