// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Phaser = require("phaser");
var Tablecloth = require("tablecloth-bucklescript/src/tablecloth.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var phaser = Phaser;

var auto = phaser.AUTO;

var canvas = phaser.CANVAS;

var headless = phaser.HEADLESS;

var webgl = phaser.WEBGL;

function createGame(renderer, parent, width, height, scene) {
  return new Phaser.Game({
              type: renderer,
              parent: parent,
              width: width,
              height: height,
              scene: scene
            });
}

function zeroCallback(fn) {
  return (function () {
      var $$this = this ;
      Curry._1(fn, $$this);
      return /* () */0;
    });
}

function dataCallback(fn) {
  return (function (data) {
      var scene = this ;
      Curry._2(fn, scene, data);
      return /* () */0;
    });
}

function createScene(key, init, preload, create, update, param) {
  var scene = new Phaser.Scene({
        key: key
      });
  if (init !== undefined) {
    scene.init = Caml_option.valFromOption(init);
  }
  if (create !== undefined) {
    scene.create = Caml_option.valFromOption(create);
  }
  if (preload !== undefined) {
    scene.preload = preload;
  }
  if (update !== undefined) {
    scene.update(Curry._1(update, scene));
  }
  return scene;
}

function toPhaserVec2(param) {
  return new (Phaser.Math.Vector2)(param[0], param[1]);
}

function toPhaserVec2F(param) {
  return new (Phaser.Math.Vector2)(param[0], param[1]);
}

function $plus$bang(param, param$1) {
  return /* tuple */[
          param[0] + param$1[0],
          param[1] + param$1[1]
        ];
}

function toIntVector(vector2F) {
  return Tablecloth.Tuple2[/* mapAll */9]((function (prim) {
                return prim | 0;
              }), vector2F);
}

function toFloatVector(vector2F) {
  return Tablecloth.Tuple2[/* mapAll */9]((function (prim) {
                return prim;
              }), vector2F);
}

var Vector2 = /* module */[
  /* toPhaserVec2 */toPhaserVec2,
  /* toPhaserVec2F */toPhaserVec2F,
  /* +! */$plus$bang,
  /* toIntVector */toIntVector,
  /* toFloatVector */toFloatVector
];

var Tween = /* module */[];

function addText(scene, x, y, text, color) {
  var text$1 = scene.add.text(x, y, text);
  return text$1.setColor(color);
}

var class_tables = [
  0,
  0,
  0
];

function setBlendMode(text, blendMode) {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env = CamlinternalOO.new_variable($$class, "");
    var env_init = function (env$1) {
      var self = CamlinternalOO.create_object_opt(0, $$class);
      self[env] = env$1;
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], 0);
}

var $$Text = /* module */[
  /* addText */addText,
  /* setBlendMode */setBlendMode
];

var class_tables$1 = [
  0,
  0,
  0
];

function addBitmapText(scene, x, y, text, color) {
  if (!class_tables$1[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env = CamlinternalOO.new_variable($$class, "");
    var env_init = function (env$1) {
      var self = CamlinternalOO.create_object_opt(0, $$class);
      self[env] = env$1;
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables$1[0] = env_init;
  }
  return Curry._1(class_tables$1[0], 0);
}

var BitMapText = /* module */[/* addBitmapText */addBitmapText];

exports.phaser = phaser;
exports.auto = auto;
exports.canvas = canvas;
exports.headless = headless;
exports.webgl = webgl;
exports.createGame = createGame;
exports.zeroCallback = zeroCallback;
exports.dataCallback = dataCallback;
exports.createScene = createScene;
exports.Vector2 = Vector2;
exports.Tween = Tween;
exports.$$Text = $$Text;
exports.BitMapText = BitMapText;
/* phaser Not a pure module */
